let modelsJson = [
    { id: 1, name: 'Calça Cargo', img: './Produtos-Venda/img/calcas/calca1/calca1-cargo.jpeg', price: [80.00, 80.00, 80.00, 80.00], sizes: ['P', 'M', 'G', 'GG'], description: 'Calça cargo preta simples e básica para qualquer ocasião' },
    { id: 2, name: 'Calça Cargo Flow', img: './Produtos-Venda/img/calcas/calca2/calcaCargo2.jpg', price: [80.00, 80.00, 80.00, 80.00], sizes: ['P', 'M', 'G', 'GG'], description: 'Se é Flow é sucesso, aproveite a nova calça da coleção!' },
    { id: 3, name: 'Calça Cargo Beje', img: './Produtos-Venda/img/calcas/calca3/calcaCargo3.jpg', price: [80.00, 80.00, 80.00, 80.00], sizes: ['P', 'M', 'G', 'GG'], description: 'Estilosa e simpática' },
    { id: 4, name: 'Saia Preta Floral', img: './Produtos-Venda/img/calcas/saia4/clothes-3.jpg', price: [80.00, 80.00, 80.00, 80.00], sizes: ['P', 'M', 'G', 'GG'], description: 'Se é Flow é sucesso, aproveite a nova calça da coleção!' },
    { id: 5, name: 'Saia Xadrez', img: './Produtos-Venda/img/calcas/saia5/saiaXadrez1.webp', price: [80.00, 80.00, 80.00, 80.00], sizes: ['P', 'M', 'G', 'GG'], description: 'Se é Flow é sucesso, aproveite a nova calça da coleção!' },
    { id: 6, name: 'Hurt Me', img: './Produtos-Venda/img/camisetas/camiseta1(hurt-me)/imagem1.webp', price: [50.00, 50.00, 50.00, 50.00], sizes: ['P', 'M', 'G', 'GG'], description: 'Camisa utilizada por aqueles que foram machucados :(' },
    { id: 7, name: 'Dragon', img: './Produtos-Venda/img/camisetas/camiseta2/camisetaDragon1.webp', price: [50.00, 50.00, 50.00, 50.00], sizes: ['P', 'M', 'G', 'GG'], description: 'Voe como um Dragão!' },
    { id: 8, name: 'Shinigami', img: './Produtos-Venda/img/camisetas/camiseta3/camisaShinigami1.webp', price: [50.00, 50.00, 50.00, 50.00], sizes: ['P', 'M', 'G', 'GG'], description: 'Camisa utilizada por aqueles que foram machucados :(' },
    { id: 9, name: 'Gengar', img: './Produtos-Venda/img/camisetas/camiseta4/camisetaGengar1.webp', price: [50.00, 50.00, 50.00, 50.00], sizes: ['P', 'M', 'G', 'GG'], description: 'Temos que pegar! Pokémon' },
    { id: 10, name: 'Astarote', img: './Produtos-Venda/img/jaqueta/jacket-5.jpg', price: [120.00, 120.00, 120.00, 120.00], sizes: ['P', 'M', 'G', 'GG'], description: 'Jaqueta muito estilosa como o Astarote' },
    { id: 11, name: 'Fly', img: './Produtos-Venda/img/jaqueta/fly1.webp', price: [120.00, 120.00, 120.00, 120.00], sizes: ['P', 'M', 'G', 'GG'], description: 'Uma Jaqueta para aqueles que voam' },
    { id: 12, name: 'Scorpion', img: './Produtos-Venda/img/moletom/moletom1/scorpion1.webp', price: [120.00, 120.00, 120.00, 120.00], sizes: ['P', 'M', 'G', 'GG'], description: 'Cuidado com o Veneno' },
    { id: 13, name: 'Dead', img: './Produtos-Venda/img/moletom/moletom2/Dead1.webp', price: [120.00, 120.00, 120.00, 120.00], sizes: ['P', 'M', 'G', 'GG'], description: 'O quê é a morte?' },
    { id: 14, name: 'Misa', img: './Produtos-Venda/img/moletom/moletom3/misa1.webp', price: [120.00, 120.00, 120.00, 120.00], sizes: ['P', 'M', 'G', 'GG'], description: 'I can be your Death Note?' },
    { id: 15, name: 'Black', img: './Produtos-Venda/img/vestidos/vestido1.webp', price: [100.00, 100.00, 100.00, 100.00], sizes: ['P', 'M', 'G', 'GG'], description: 'Um vestido bonito' },
];
